name: Go Ci

on:
  push:
    branches:
      - '**'

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version-file: 'go.mod'
          cache: true

      - name: Check formatting
        run: |
          if [ -n "$(go fmt ./...)" ]; then
            echo "Fehler: Code ist nicht korrekt formatiert! Bitte 'go fmt ./...' lokal ausführen."
            exit 1
          fi

      - name: Run Go Vet (Native Linter)
        run: go vet ./...

      - name: Check Code Modernization (go fix)
        run: go fix ./...

      - name: Build Code
        run: go build -v ./...
